// <auto-generated />
namespace DataMatrixPrinter.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IsEnableEntities2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsEnableEntities2));
        
        string IMigrationMetadata.Id
        {
            get { return "201802221030030_IsEnableEntities2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
